word_embeddings:
  # Two types of word embedding algorithm (word2vec and glove) are supported.
  # Just set the default to empty string to disable the word embeddings
  default: glove
  word2vec:
    path: ../../data/input/word_embeddings/GoogleNews-vectors-negative300.bin
    dimension: 300
    binary: True
  glove:
    path: '/home/xxliu10/bigdata/vec25.txt'
    dimension: 25
    length: 400000

